# Install with `pre-commit install`
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.16.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
    -   id: black