services:
  client_test:
    image: cypress/included:9.1.0
    working_dir: /tests
    volumes:
      # USER passthrough
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # mount tests - readonly
      - ${PWD}/cypress.json:/tests/cypress.json:ro
      - ${PWD}/cypress:/tests/cypress:ro
      # mount reports - writeable
      - ${PWD}/reports:/tests/reports:rw
    entrypoint: ["cypress"]
    command: ["run"]
