name: Cypress Browser Tests

on: 
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config: baseUrl=http://localhost:8000
          start: make run
          wait-on: 'http://localhost:8000'
