name: Test

on:
  push:
    paths:
      - '**'
  # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
  # schedule
  # workflow_dispatch - with params

#defaults:
#  run:
#    working-directory: client

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Unit Tests
      run: make test
    - name: Archive test report
      uses: actions/upload-artifact@v2
      with:
          name: report.html
          path: reports/report.html